import { Col, Container, Row } from "reactstrap";
import classes from "./GenerateDetails.module.css";
const GenerateDetails = () => {
  return (
    <>
      <p className={classes.head}> <span className={classes.head2}>Generate : </span> Add details</p>
      <div
        className={classes.back}
        style={{
          position: "absolute",
          top: "10%",
          left: "78%",
          textDecoration: "underline",
          color: "#000000",
        }}
      >
        <a onClick={() => handleBack()}>back</a>
      </div>

      <form>
        <Container fluid className={classes.cont}>
          <Row className={classes.rowe}>
            <Col md={2} sm={6} xs={6}>
              <label for="name" className={classes.detail}>
                Name of the company
              </label>
            </Col>
            <Col md={10} sm={6} xs={6}>
              <input type="text" name="CompanyName" className={classes.fill} />
            </Col>
          </Row>
          <Row className={classes.rowe}>
            <Col md={2} sm={6} xs={6}>
              {" "}
              <label for="nature" className={classes.detail}>
                Nature of work
              </label>
            </Col>
            <Col md={10} sm={6} xs={6}>
              <input type="text" name="natureOfWork" className={classes.fill} />
            </Col>
          </Row>
          <Row className={classes.rowe}>
            <Col md={2} sm={6} xs={6}>
              {" "}
              <label for="generated" className={classes.detail}>
                Generated by ( technician )
              </label>
            </Col>
            <Col md={10} sm={6} xs={6}>
              <input
                type="text"
                name="generated"
              
                className={classes.fill}
              />
            </Col>
          </Row>
          <button type="submit" className={classes.sub}>
            SUBMIT
          </button>
        </Container>
      </form>
      <Container className={classes.footer}>
          <p> copyright aivara | terms and coditions </p>
      </Container>
    </>
  );
};

export default GenerateDetails;
