import Head from "next/head";

import Footer from "../components/Footer"
import Header from "../components/Header"
import classes from "../components/LoginForm.module.css"
import LoginForm from "../components/LoginForm"
import { useState } from "react";







export default function Home() {
  const [show, setShow] = useState(false)
  return (
    < >
      <Head>
        <title>AIVARA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Sora:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet"/>
<script src="https://kit.fontawesome.com/4a4ddc9f6c.js" crossorigin="anonymous"></script>
    
     
      </Head>
      
<LoginForm/>
   <Footer></Footer>
    
        
      </>
        
         
      
    
  );
}
