import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer"
import Header from "../components/Header"
import LoginForm from "../components/LoginForm"
import { useState } from "react";



export default function Home() {
  const [show, setShow] = useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>AIVARA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
<script src="https://kit.fontawesome.com/4a4ddc9f6c.js" crossorigin="anonymous"></script>
    
     
      </Head>

      <main>
      <>
         <Header show={show} setShow={setShow}>
         </Header>
         <LoginForm show={show}/>
         <Footer></Footer>
         </>
      </main>
    </div>
  );
}
